# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0cPYgn903ywwI2mEbY7JizhVwX4Snbr
"""

from datetime import datetime

import numpy as np

# image read libraries
from PIL import Image
import matplotlib.pyplot as plt

mypath = "G:\Mijn Drive\projecten\wintersport_projectje/"

img=Image.open(mypath+'achtergrond.png')

def create_text(vertrekdatum):
#vertrekdatum needs to be in YYYY-MM-DD format
    my_date = datetime.strptime(vertrekdatum, "%Y-%m-%d")
    today = datetime.now()
    delta= my_date-today
    a= "JAAAAAAAA, Let's GO"
    b= 'Bijna, nog '+ str(delta.days)+ ' dagen :)'
    c= 'Nee, nog '+ str(delta.days)+ ' dagen :('
    if delta.days < 10:
        return (b)
    elif delta.days <1:
        return (a)
    else:
        return (c)


def make_image(data,size=(20, 15), dpi=80):
    fig = plt.figure()
    fig.set_size_inches(size)
    ax = plt.Axes(fig, [0., 0., 1., 1.])
    ax.set_axis_off()
    fig.add_axes(ax)
    plt.set_cmap('hot')
    plt.text(80,100,'Gaan we nou al op wintersport?',fontsize=80)
    plt.text(220,300, create_text('2022-03-22'),fontsize=75)
    ax.imshow(data, aspect='equal',interpolation="nearest")

make_image(img)
plt.savefig("hoe_lang_nog", format='png', bbox_inches='tight')